INSERT INTO MATERIALGROUP (GroupName) values ('EarthWork');
INSERT INTO MATERIALGROUP (GroupName) values ('Concrete');
INSERT INTO MATERIALGROUP (GroupName) values ('Cement');
INSERT INTO MATERIALGROUP (GroupName) values ('Steel');
INSERT INTO MATERIALGROUP (GroupName) values ('Gravel');
INSERT INTO MATERIALGROUP (GroupName) values ('Sand');
INSERT INTO MATERIALGROUP (GroupName) values ('Metal');
INSERT INTO MATERIALGROUP (GroupName) values ('CementConsumption');
INSERT INTO MATERIALGROUP (GroupName) values ('SteelConsumption');
INSERT INTO MATERIALGROUP (GroupName) values ('GravelConsumption');
INSERT INTO MATERIALGROUP (GroupName) values ('SandConsumption');
INSERT INTO MATERIALGROUP (GroupName) values ('MetalConsumption');
INSERT INTO MATERIALGROUP (GroupName) values ('Expenses');
INSERT INTO MATERIALGROUP (GroupName) values ('Machinery');
INSERT INTO MATERIALGROUP (GroupName) values ('Diesel');
INSERT INTO MATERIALGROUP (GroupName) values ('NMR');
INSERT INTO MATERIALGROUP (GroupName) values ('RMCConsumed');

INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Ex-200',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Ex-220',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Ex-110',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Ex-100',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('JCB',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Vibromax',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Tractor Dozer',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Chain Dozer',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Self Loader',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Tippers',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Tractor',14);
INSERT INTO MachineryNamesMaster (Name,GroupId) values ('Bolero Pick Up',14);


INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Break Down',14);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('No Work',14);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Due to Rain',14);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Working',14);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Jungle Cleance',1);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Bed Cutting',1);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Slope Cutting',1);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Back Filling',1);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Bank Filling',1);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Cross Banda',1);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Loading',1);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('M-10',2);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('M-15',2);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('M-20',2);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('M-25',2);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('PCC',2);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('RCC',2);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Mass Concrete',2);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Revetment',2);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Gravel',5);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Satru',5);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Stone',7);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Satru',7);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('10 MM',7);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('20 MM',7);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('30 MM',7);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('40 MM',7);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('12 MM',7);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('1/4 MM',7);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('HSD',15);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Petrol',15);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('43 Grade OPC',3);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('53 Grade OPC',3);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Bulk',3);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('8 MM',4);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('10 MM',4);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('12 MM',4);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('14 MM',4);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('16 MM',4);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Sand',6);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Sand',17);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Cement',17);
INSERT INTO ParticularsMaster (ParticularsName,GroupId) values ('Metal',17);

INSERT INTO UoMMaster (UoMName,GroupId) values ('Cum',1);
INSERT INTO UoMMaster (UoMName,GroupId) values ('Sqm',1);
INSERT INTO UoMMaster (UoMName,GroupId) values ('Cum',2);
INSERT INTO UoMMaster (UoMName,GroupId) values ('Sqm',2);
INSERT INTO UoMMaster (UoMName,GroupId) values ('Bags',3);
INSERT INTO UoMMaster (UoMName,GroupId) values ('Mts',3);
INSERT INTO UoMMaster (UoMName,GroupId) values ('Mts',4);


Insert into LocationMaster (LocationName) values ('Hyderabad');
Insert into LocationMaster (LocationName) values ('Mumbai');
Insert into LocationMaster (LocationName) values ('New Delhi');